<?php

/**
 * @file
 * Primary module hooks for Reward module.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function reward_theme(): array {
  return [
    'reward' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for reward templates.
 *
 * Default template: reward.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the reward information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_reward(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function reward_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish rewards.
      $storage = \Drupal::entityTypeManager()->getStorage('reward');
      $reward_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($reward_ids) as $reward) {
        $reward->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize rewards.
      $storage = \Drupal::entityTypeManager()->getStorage('reward');
      $reward_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($reward_ids) as $reward) {
        $reward->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function reward_user_predelete(UserInterface $account): void {
  // Delete rewards that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('reward');
  $reward_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($reward_ids)
  );
}
