<?php

/**
 * @file
 * Install, update and uninstall functions for the Reward module.
 */

use Drupal\user\RoleInterface;

/**
 * Implements hook_schema().
 */
function reward_schema(): array {
  $schema['reward_claim'] = [
    'description' => 'Record the reward claim.',
    'fields' => [
      'uid' => [
        'description' => 'The user.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ],
      'reward_id' => [
        'description' => 'The reward.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ],
      'timestamp' => [
        'description' => 'Timestamp of the claiming.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
        'size' => 'big',
      ],
    ],
  ];
  return $schema;
}


/**
 * Implements hook_install().
 */
function reward_install() {
  // Append rest plugin permissions to authenticated role.
  $permissions = [
    'view reward',
  ];
  user_role_grant_permissions(RoleInterface::AUTHENTICATED_ID, $permissions);
}
