<?php

/**
 * @file
 * Primary module hooks for Reward module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function reward_theme(): array {
  return [
    'reward' => ['render element' => 'elements'],
    'reward_claim' => ['render element' => 'elements'],
  ];
}

/**
 * Implements hook_entity_base_field_info().
 */
function reward_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];
  if ($entity_type->id() === 'task') {
    $fields['rewards'] = BaseFieldDefinition::create('entity_reference')
      ->setName('Rewards')
      ->setLabel(t('Rewards belongs to the task.'))
      ->setComputed(TRUE)
      ->setCardinality(FieldStorageDefinitionInterface::CARDINALITY_UNLIMITED)
      ->setClass('\Drupal\reward\RewardItemList')
      ->setSetting('target_type', 'reward')
      ->setSetting('handler', 'default')
      ->setDisplayConfigurable('view', TRUE)
      ->setDisplayOptions('view', [
        'label' => 'hidden',
        'weight' => -5,
      ]);
  }

  if ($entity_type->id() === 'reward') {
    $fields['claims'] = BaseFieldDefinition::create('entity_reference')
      ->setName('Claims')
      ->setLabel(t('Claims of this reward.'))
      ->setComputed(TRUE)
      ->setCardinality(FieldStorageDefinitionInterface::CARDINALITY_UNLIMITED)
      ->setClass('\Drupal\reward\RewardClaimItemList')
      ->setSetting('target_type', 'reward_claim')
      ->setSetting('handler', 'default')
      ->setDisplayConfigurable('view', TRUE)
      ->setDisplayOptions('view', [
        'label' => 'hidden',
        'weight' => -5,
      ]);

    $fields['claim_info'] = BaseFieldDefinition::create('reward_claim_info')
      ->setName('Claim info')
      ->setLabel(t('Claim info of the reward for current user'))
      ->setComputed(TRUE)
      ->setClass('\Drupal\reward\ClaimInfoList')
      ->setCardinality(1) // You only need this if your computed field is multi-value.
      ->setDisplayConfigurable('view', TRUE)
      ->setDisplayOptions('view', [
        'label' => 'hidden',
        'weight' => -5,
      ]);
  }
  return $fields;
}

function reward_entity_base_field_info_alter(&$fields, \Drupal\Core\Entity\EntityTypeInterface $entity_type) {
  // Alter the my_module_text field to use a custom class.
  if ($entity_type->id() == 'ledger' && !empty($fields['source'])) {
    /** @var BaseFieldDefinition $field */
    $field = $fields['source'];
    $settings = $field->getSettings();
    $settings['entity_type_ids'] = ['reward_claim' => 'reward_claim'] + $settings['entity_type_ids'];
    $settings['reward_claim'] = [
      'handler' => "default:reward_claim",
      'handler_settings' => [
        'target_bundles' => NULL,
      ],
    ];
    $field->setSettings($settings);
  }
}

/**
 * Prepares variables for reward templates.
 *
 * Default template: reward.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the reward information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_reward(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Prepares variables for reward claim templates.
 *
 * Default template: reward-claim.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the reward claim information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_reward_claim(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function reward_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish rewards.
      $storage = \Drupal::entityTypeManager()->getStorage('reward');
      $reward_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($reward_ids) as $reward) {
        $reward->set('status', FALSE)->save();
      }

      // Anonymize reward claims.
      $storage = \Drupal::entityTypeManager()->getStorage('reward_claim');
      $reward_claim_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($reward_claim_ids) as $reward_claim) {
        $reward_claim->setOwnerId(0)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize rewards.
      $storage = \Drupal::entityTypeManager()->getStorage('reward');
      $reward_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($reward_ids) as $reward) {
        $reward->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function reward_user_predelete(UserInterface $account): void {
  // Delete rewards that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('reward');
  $reward_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($reward_ids)
  );

  // Delete reward claims that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('reward_claim');
  $reward_claim_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($reward_claim_ids)
  );
}
