<?php

/**
 * @file
 * Install, update and uninstall functions for the Reward module.
 */

use Drupal\user\RoleInterface;


/**
 * Implements hook_install().
 */
function reward_install() {
  // Append rest plugin permissions to authenticated role.
  $permissions = [
    'view reward',
    'restful post reward_claim',
  ];
  user_role_grant_permissions(RoleInterface::AUTHENTICATED_ID, $permissions);
}
